# makeCacheMatrix: This function creates a special "matrix" object that can cache its inverse.
makeCacheMatrix <- function(x = matrix()) {
        invmatrix <- NULL              ## the inv matrix
        set <- function(y) {           ## function changes matrix stored in the makeCacheMatrix. Only used to change the matrix.
                x <<- y                ## subs the matrix x with y in makeCacheMatrix.
                invmatrix <<- NULL     ## restores to NULL the value of the inv matrix invmatrix.
        }
        get <- function() x            ## returns the matrix x. Does not require any input.
        setinv <- function(invM) invmatrix <<- invM ## does not calculate invM, is used to store the value of input matrix invM into makeCacheMatrix.
        getinv <- function() invmatrix ## does not calculate inv, simply returns the value of input inv matrix m to the main function makeCacheMatrix.
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)          ## the function list assigned to makeCacheMatrix
        
}

# cacheSolve: This function computes the inverse of the special "matrix" returned by makeCacheMatrix.
cacheSolve <- function(x, ...) { 
        invmatrix <- x$getinv()         
        if(!is.null(invmatrix)) {      ## check that invmatrix is not null and return it.
                message("getting cached data")
                return(invmatrix)
        }
        data <- x$get()                ## gets the matrix passed to makeCacheMatrix.
        invmatrix <- solve(data, ...)  ## solves for the inverse matrix of data.
        x$setinv(invmatrix)            ## stores the inv matrix in the object generated by makeCacheMatrix.
        invmatrix                             
}

#testing
#source('makeCacheMatrix.R')
#mydata<-rnorm(36)
#mymatrix<- matrix(mydata, nrow=6, ncol=6)
#mymatrix
#myinv<-solve(mymatrix)
#myinv
#a<-makeCacheMatrix(mymatrix)
#b<-cacheSolve(a)
